apiVersion: v1
kind: Service
metadata:
  name: minecraft-svc
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
    - port: 25565
      name: minecraft
      targetPort: 25565
      nodePort: 30065
    - port: 19132
      name: bedrock
      targetPort: 19132
      nodePort: 30132

