apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: shaker242/minecraft:bedrock
        ports:
        - containerPort: 25565
        - containerPort: 19132
        resources:
          limits:
            cpu: 1.5
            memory: 2Gi

