apiVersion: v1
kind: Service
metadata:
  name: bedrock-svc
spec:
  type: NodePort
  selector:
    app: bedrock
  ports: # NOTE THE BELOW PORT MAPPINGS
    - port: 25565
      name: minecraft
      targetPort: 25565
      nodePort: 30065
    - port: 19132
      name: bedrock
      targetPort: 19132
      nodePort: 30132

