apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "world-one-pvc"
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "world-two-pvc"
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
