# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: harry-potter-pv
#   namespace: minecraft
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   nfs:
#     path: /nfs/manual/minecraft/HARRYPOTTERV7
#     server: 172.16.1.5
#   persistentVolumeReclaimPolicy: Retain
# ---
# apiVersion: "v1"
# kind: "PersistentVolumeClaim"
# metadata:
#   name: "harry-potter-pvc"
#   namespace: minecraft
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: ""
#   volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zombie-apocalypse-pv
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /nfs/manual/minecraft/ZOMBIEAPOCALYPSE
    server: 172.16.1.5
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "zombie-apocalypse-pvc"
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
