
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-az-prod
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minecraft-az
  namespace: minecraft-az-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-az
  template:
    metadata:
      labels:
        app: minecraft-az
    spec:
      containers:
        - name: minecraft-az
          image: ghcr.io/ocpdude/minecraft:latest
          ports:
            - containerPort: 25565
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2G
            requests:
              cpu: '0'
              memory: '0'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
