# LoadBalancer Type only
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  namespace: minecraft
spec:
  type: LoadBalancer
  selector:
    deployment: minecraft
  loadBalancerIP: IP_ADDRESS
  ports:
    - port: 25565
      targetPort: 25565
