---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zombie-apocalypse-pv
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /nfs/path/to/minecraft/ZOMBIEAPOCALYPSE
    server: 172.16.1.5
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "zombie-apocalypse-pvc"
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
