name: Minecraft Azure Deploy

on:
#   pull_request:
#     branches:
#     - main
#     paths:
#     - 'Dockerfile'
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io
  
jobs: 
   az-deploy:
      runs-on: ubuntu-latest
      environment: aks-production
      steps:
         - name: checkout-repo
           uses: actions/checkout@v3
      
         - uses: Azure/k8s-set-context@v2
           with:
              kubeconfig: ${{ secrets.AZURE_KUBE_CONFIG }}

         # Set the target AKS cluster.
         # - uses: Azure/aks-set-context@v1
         #   with:
         #      creds: '${{ secrets.AZURE_CREDENTIALS }}'
         #      cluster-name: bluestar
         #      resource-group: bluestar-rg

         - uses: Azure/k8s-deploy@v3.1
           with:
              action: deploy
              namespace: minecraft-az-prod
              manifests: |
                 manifests/azure-deployment.yml
                 manifests/azure-service.yml
              images: |
                 '${{ env.REGISTRY }}/ocpdude/minecraft:latest'
                 
   remove-staging:
     needs: az-deploy
     runs-on: ubuntu-latest

     steps:
     - name: 'Install tools'
       uses: redhat-actions/openshift-tools-installer@v1
       with:
        oc: "latest"
        
     - uses: Azure/k8s-set-context@v2
       with:
          kubeconfig: ${{ secrets.OPENSHIFT_KUBE_CONFIG }}
              
     - name: Authenticate and set namespace
       uses: redhat-actions/oc-login@v1
       with:
         openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
         openshift_username: ${{ secrets.OPENSHIFT_USER }}
         openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
         certificate_authority_data: ${{ secrets.REDCLOUD_CA }}
         insecure_skip_tls_verify: true

     - name: 'Remove Staging'
       run: oc delete ns minecraft-az-staging
       continue-on-error: true
            
     - name: 'Remove Staging Environment'
       uses: strumwolf/delete-deployment-environment@v2
       with:
           token: ${{secrets.GITHUB_TOKEN}}
           environment: openshift-staging
           onlyRemoveDeployments: true
