name: Bedrock Builder  

on:
  push:
    branches:
    - main
    paths:
    - 'bedrock/Dockerfile'
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io 
  
jobs:

#   linter:
#     # Let's lint the Dockerfile before build 
#     uses: ocpdude/reusable/.github/workflows/linter.yaml@main
#     with:
#       language: hadolint

  build_push:
#     needs: linter
    name: Build image
    runs-on: [ ubuntu-latest ] 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Context
      id: buildx-context
      run: |
        docker context create builders || docker context use builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        endpoint: builders
            
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to Registries
      uses: docker/build-push-action@v4
      with:
        context: ./bedrock
        push: true
        tags: |
          docker.io/shaker242/bedrock:latest
          docker.io/shaker242/bedrock:1.19.51
          ${{env.REGISTRY}}/ocpdude/bedrock:latest
          ${{env.REGISTRY}}/ocpdude/bedrock:1.19.51
          
  check_quality:
    needs: build_push
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Scanning Image
      continue-on-error: true
      uses: azure/container-scan@v0
      with:
        image-name: ${{env.REGISTRY}}/ocpdude/bedrock:latest
        run-quality-checks: true
