name: Scan app

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
    
jobs:
  codeql:
    name: Code Scan
    uses: ocpdude/reusable/.github/workflows/codeql.yaml@main
