name: Linting Dockerfiles 🐳
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - Dockerfile

 workflow_dispatch:

jobs:
  lint-docker:
    uses: ocpdude/reusable/.github/workflows/lint-docker.yaml@main
    with:
      file-path: Dockerfile