name: Linting Kubernetes ☸️
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - 'manifests/**.yaml'
    - 'manifests/**.yml'
    - 'bedrock/manifests/**.yaml'
    - 'bedrock/manifests/**.yml'
        
 workflow_dispatch:

jobs:
  k8s-lint:
    # uses: ocpdude/reusable/.github/workflows/linter.yaml@main
    # with:
    #   language: YamlLint, kubeval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v2.0
      - uses: azure/k8s-lint@v1
        with:
          manifests: |
              manifests/*.yml
