name: Linting Kubernetes ☸️
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - 'manifests/**.yaml'
    - 'manifests/**.yml'
    - 'bedrock/manifests/**.yaml'
    - 'bedrock/manifests/**.yml'
        
 workflow_dispatch:

jobs:
    k8s-lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: List files and store in environment variable
          run: echo "MANIFESTS=$(printf '%s\n' ./manifests/*.yaml)" >> $GITHUB_ENV  
                  
        - uses: azure/k8s-lint@v1
          with:
            manifests: |
              ${{ env.MANIFESTS }}
