name: Linting Kubernetes ☸️
on:
 pull_request:
    branches:
    - '!main'
    paths: 
    - 'manifests/**.yaml'
    - 'manifests/**.yml'
        
 workflow_dispatch:

jobs:

  lint-k8s:
    uses: ocpdude/reusable/.github/workflows/lint-k8s.yaml@main
    with:
      file-path: ./manifests