name: Minecraft Builder  

on:
  pull_request:
    branches:
    - main
    paths:
    - 'Dockerfile'
  workflow_dispatch:
  
jobs:

  lint-docker:
    uses: ocpdude/reusable/.github/workflows/lint-docker.yaml@main
    with:
      file-path: Dockerfile

  security-checks:
    permissions:
      contents: read
      security-events: write
      actions: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [ lint-docker ]
    steps:
      - uses: actions/checkout@v4
      - name: Build the test image
        run: docker build . --tag localbuild/testimage:latest
      - name: Grype scan the test image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: localbuild/testimage:latest
          fail-build: false
          severity-cutoff: critical

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['deploy to staging']
            })
