name: Minecraft Builder  

on:
  pull_request:
    branches:
    - main
#     paths:
#     - 'Dockerfile'
  workflow_dispatch:
   
env:
  REGISTRY: ghcr.io 
  
jobs:

  lint-docker:
    uses: ocpdude/reusable/.github/workflows/lint-docker.yaml@main
    with:
      file-path: Dockerfile

  security-checks:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    needs: [ lint-docker ]
    steps:
      - uses: actions/checkout@v4
      - name: Build the test image
        run: docker build . --tag localbuild/testimage:latest
      - name: Grype scan the test image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: false
          severity-cutoff: critical
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

  build-deployment:
    needs: [ security-checks ]
    runs-on: ubuntu-latest
    steps:
      # - name: Get the date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%m%d')"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Minecraft version
        id: minecraft_version
        run: echo "::set-output name=version::$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{env.REGISTRY}}/ocpdude/minecraft:${{ steps.minecraft_version.outputs.version }}
            ${{env.REGISTRY}}/ocpdude/minecraft:latest
            shaker242/minecraft:${{ steps.minecraft_version.outputs.version }}
            shaker242/minecraft:latest

  check_quality:
    needs: build-deployment
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Scanning Image
        continue-on-error: true
        uses: azure/container-scan@v0
        with:
          image-name: ${{env.REGISTRY}}/ocpdude/minecraft:latest
          run-quality-checks: true