name: Minecraft OpenShift Staging

on:
  pull_request:
    types:
      - labeled
    # paths:
    #   - '!.github/workflows/**'

  workflow_dispatch:
env:
  REGISTRY: registry.redcloud.land
jobs: 
  deploy_staging-okd:
    permissions:
      statuses: write
    environment: openshift-staging
    name: 'Staging Minecraft'
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'deploy to staging'
    steps:
      - name: 'Establish Wireguard Connection'
        run: |
          sudo apt install wireguard resolvconf
          echo '${{ secrets.WG_PRIVATE_KEY }}' > privatekey
          echo '${{ secrets.WG_PRESHARED_KEY }}' > presharedkey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 172.16.100.4/26
          sudo ip link set dev wg0 up
          sudo wg set wg0 listen-port 51820 private-key privatekey peer '${{ secrets.WG_PEER_PUBKEY }}' preshared-key presharedkey endpoint '${{ secrets.WG_ENDPOINT }}' persistent-keepalive 25 allowed-ips '${{ secrets.WG_ALLOWED_IPS }}'
          sudo route add -net 172.16.1.0/26 gw 172.16.100.1 wg0
          sudo resolvconf -u && echo "nameserver 172.16.1.1" | sudo tee /etc/resolvconf/resolv.conf.d/head && sudo resolvconf -u

      - name: Install CA
        run: |
          sudo echo '${{ secrets.REDCLOUD_CA }}' | sudo tee /usr/local/share/ca-certificates/redcloud.crt
          sudo update-ca-certificates

      - name: 'Checkout code'
        uses: actions/checkout@v4
      - name: Extract Minecraft version
        id: minecraft_version
        run: echo "VERSION=$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')" >> $GITHUB_ENV
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to RedCloud Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NEXUS_USER }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{env.REGISTRY}}/minecraft/minecraft-staging:${{ env.VERSION }}
      - name: 'Install tools'
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "latest"
      - name: 'Authenticate and set namespace'
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_username: ${{ secrets.OPENSHIFT_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          insecure_skip_tls_verify: true
      - name: 'Create Namespace'
        run: |
          oc new-project minecraft-okd-staging
      - name: 'Deploy to Staging'
        uses: redhat-actions/oc-new-app@v1
        with:
          app_name: minecraft
          registry_hostname: ${{ env.REGISTRY }}
          image: ${{env.REGISTRY}}/minecraft/minecraft-staging:${{ env.VERSION }}
          namespace: minecraft-okd-staging
          
