name: test action
on:  
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Minecraft version
        id: minecraft_version
        run: echo "VERSION=$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')" >> $GITHUB_ENV
        shell: bash
      # - name: Set VERSION as env variable
      #   run: echo "VERSION=${{ steps.minecraft_version.outputs.VERSION }}" >> $GITHUB_ENV

      # - name: Extract Minecraft version
      #   id: minecraft_version
      #   run: |
      #     echo "::setOutput name=version::$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{env.REGISTRY}}/ocpdude/minecraft:${{ env.VERSION }}
