name: test action
on:  
  workflow_dispatch:
jobs:
  build-deployment:
    runs-on: ubuntu-latest
    steps:
      # - name: Get the date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%m%d')"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Minecraft version
        id: minecraft_version
        run: |
          echo "::setOutput name=version::$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')"
          echo "VERSION=$(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')">> $GITHUB_ENV
          echo "Output version: $(ls minecraft* | awk -F"." 'OFS="." {print $2,$3,$4}')"
          echo "Environment version: $VERSION"

          
