name: Wireguard Test

on:
  workflow_dispatch:
  
jobs: 

  wireguard:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard

      - run: sudo wg genkey > privatekey

      - run: sudo ip link add dev wg0 type wireguard

      - run: sudo ip address add dev wg0 192.168.2.1/24

      - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer gAZM0Q5U57P61Ifb0YHsA1hZPMF80uYGX4Ccyxf0NTY= allowed-ips 172.16.1.0/26 endpoint 96.255.45.219:51820

      - run: sudo ip link set up dev wg0

      - run: ping 172.16.1.9
